### ISSUE TITLE
humbledownload.js script returns error

### ISSUE THREAD

**Issue by ghost** [AntonFagerberg/humble_download#1]
It seems the `humbledownload.js` script doesn't work anymore. When executed in my Firefox 40, the Console returns the following error:

`TypeError: $r.attr(...) is undefined`

This is probably due to an update in the way the library is displayed, because there is indeed no `data-human-name=""` attribute anymore in the `<a class="row">` elements.

Any chance this javascript will be updated?

**Comment by AntonFagerberg** [comment]
Thanks for the report! I'll take a look at it in a little while. It's probably a layout change as you say so it shouldn't be that hard to fix.

**Comment by AntonFagerberg** [comment]
Alright, the script is now updated and should work with the new design. It's totally rewritten so that it does "real" requests and uses the JSON responses instead of parsing the HTML.

Fixed in commit a9a2beb1098cc9007381f4fbfa9e64808e2d1333

**Comment by ghost** [comment]
I confirm your patch fixes the issue. Thank you!
Closing.
